#!/bin/sh

set -e

if [ $# -eq 0 ]
then
    echo Usage:   $0 TESTDIR '[IMPLEMENTATION CMDLINE...]'
    echo Command for implementation must be usable from test directory.
    dir=$( cd "$(dirname "$0")"/.. ; cd . ; cd -P -- -)
    tdir=basic
    [ "$(dirname "$0")" != "." ] && tdir="$dir/tests/$tdir"
    echo Example: "$0" "$tdir" java -cp "$dir"/java nz.mwh.wg.Start
    exit 1
fi
testdir=$1
shift

if [ $# -eq 0 ]
then
    dir=$(cd "$(dirname "$0")/../java" && pwd -P)
    set -- java -cp "$dir" nz.mwh.wg.Start
    echo "Defaulting to implementation: $*"
    echo
fi


total=0
passed=0
failed=0

fail() {
    printf "FAIL      %s\n" "$1"
}
if [ -t 1 ]
then
    hl=$(tput rev || true)
    nm=$(tput sgr0 || true)
    fail() {
        printf 'FAIL      %s\r%s%s%s\n' "$1" "$hl" "$testcase" "$nm"
    }
fi

cd "$testdir"
rm -rf _test_data
mkdir _test_data
for testcase in *.grace
do
    total=$((total + 1))
    grep -o -E '//: .*' "$testcase" | cut -b 5- > _test_data/test.expected
    should_error=$(printf '%s\n' "$testcase" | grep -o _error || true)
    short=$(printf "$testcase" | sed -e 's/_/ /g; s/error/(error)/; s/\.grace$//;')
    printf '%-40s' "${short}"
    if ! "$@" "$testcase" > _test_data/test.out 2> _test_data/test.err
    then
        if [ "$should_error" ]
        then
            printf '|x  | '
            echo "PASS"
            passed=$((passed + 1))
        else
            printf '|%sX%s  | ' "$hl" "$nm"
            echo "exit code $!" > _test_data/"${testcase%.grace}".exit
            fail "Error exit"
            failed=$((failed + 1))
        fi
    elif ! cmp -s _test_data/test.out _test_data/test.expected
    then
        printf '| O | '
        fail "Wrong output"
        failed=$((failed + 1))
        diff -u _test_data/test.expected _test_data/test.out > _test_data/"${testcase%.grace}".diff || true
    elif [ -s _test_data/test.err ]
    then
        printf '| o%sE%s| ' "$hl" "$nm"
        fail "stderr"
        failed=$((failed + 1))
        cp _test_data/test.err _test_data/"${testcase%.grace}".err
    elif [ "$should_error" ]
    then
        printf '|%s!%s  | ' "$hl" "$nm"
        fail "Should be error"
        failed=$((failed + 1))
    else
        printf '| o | '
        echo PASS
        passed=$((passed + 1))
    fi
done

rm -f _test_data/test.{out,err,expected}

echo
if [ $failed -gt 0 ]
then
    echo "Passed $passed/$total; failed $failed/$total"
    exit 1
else
    echo Passed $passed/$total
fi

# vim:set expandtab sw=4 ts=4:
