#!/bin/sh

set -e

testdir=$1
shift

if [ $# -eq 0 ]
then
    dir=$(cd "$(dirname "$0")/../java" && pwd -P)
    set -- java -cp "$dir" nz.mwh.wg.Start
    echo "Defaulting to implementation: $*" 
    echo
fi


total=0
passed=0
failed=0

cd "$testdir"
rm -rf _test_data
mkdir _test_data
for testcase in *.grace
do
    total=$((total + 1))
    grep -o -E '//: .*' "$testcase" | cut -b 5- > _test_data/test.expected
    should_fail=$(printf '%s\n' "$testcase" | grep -o _fail || true)
    printf '%-40s' "$testcase"
    if ! "$@" "$testcase" > _test_data/test.out 2> _test_data/test.err
    then
        if [ "$should_fail" ]
        then
            echo "PASS      Expected error"
            passed=$((passed + 1))
        else
            echo "exit code $!" > _test_data/"${testcase%.grace}".exit
            echo "FAIL      Error exit"
            failed=$((failed + 1))
        fi
    elif ! cmp -s _test_data/test.out _test_data/test.expected
    then
        echo "FAIL      Wrong output"
        failed=$((failed + 1))
        diff -u _test_data/test.expected _test_data/test.out > _test_data/"${testcase%.grace}".diff || true
    elif [ -s _test_data/test.err ]
    then
        echo "FAIL      stderr"
        failed=$((failed + 1))
        cp _test_data/test.err _test_data/"${testcase%.grace}".err
    elif [ "$should_fail" ]
    then
        echo "FAIL      Should be error"
        failed=$((failed + 1))
    else
        echo PASS
        passed=$((passed + 1))
    fi
done

rm -f _test_data/test.{out,err,expected}

echo
if [ $failed -gt 0 ]
then
    echo "Passed $passed/$total; failed $failed/$total"
else
    echo Passed $passed/$total
fi
